# Generated by Django 4.0.5 on 2022-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('telegram_username', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
