# Generated by Django 4.0.5 on 2022-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[['cake', 'Cake'], ['sweets', 'Sweets'], ['bake', 'Bake']], max_length=10)),
            ],
        ),
    ]
